### ISSUE TITLE
Unable to set user data directory

### ISSUE THREAD

**Issue by Daneszkk** [Zaarrg/TTVDropBot#11]
When i paste the path for the chrome profile, the program exits instantly.
I even tried to put it in settings manually, but i got like 10 rows of errors.
Is this a known issue, or am I messing up something?

**Comment by Aerosyth** [comment]
Make sure you don't have quotes around your path. That happened with me, but removing the quotes seems to fix it and allow it to continue.

**Comment by Daneszkk** [comment]
If i do it like this, it crashes.
![image](https://user-images.githubusercontent.com/87356185/125786764-66be7a05-3a34-42c3-a875-4f2b29e420d3.png)
If i do manually, with or even without quotes, it gives me this:
![image](https://user-images.githubusercontent.com/87356185/125786908-ece7b07e-71d9-4ea1-be54-45cdc8f28873.png)
Can you like show me how is it in your settings file?

**Comment by Aerosyth** [comment]
My apologies, I misunderstood and was thinking you were talking about the Chrome executable path. I actually don't set a data directory, which would explain why I'm not having issues. One thing I have noticed that could possibly be an issue is I see a spelling mistake in the error output. 

at GetPaths (C:\Users\cameron.lee\Desktop\TTVDropBot\src\functions\Get**Pahts**.js:12:30)

I see that "GetPahts.js" is spelled wrong, where I think it should be "GetPaths.js" This could be absolutely nothing but is the only thing I see standing out to me. I'm fairly ignorant of JavaScript, so I can't really reconfigure and test.

**Comment by Zaarrg** [comment]
@Daneszkk The Error you are getting is a result of the settings.json being corrupted or the settings.json contain something it shouldn't. The Bot cant read it. Try to delete the settings.json and start the Bot again, this should create a vaild settings.json, then make sure while providing the google chrome path and user path that you dont add anything or misspell it.

**Comment by Daneszkk** [comment]
Nah, i figured it out, maybe this can help others. So, chrome gave me the path this way: C:\Users\Danesz\AppData\Local\Google\Chrome\User Data\Default
And in the settings.json it have to be with double slashes, that was the only problem.
