### ISSUE TITLE
No rust drops available 

### ISSUE THREAD

**Issue by VozDeOuro** [Zaarrg/TTVDropBot#12]
![image](https://user-images.githubusercontent.com/36045463/125943105-a453298a-05fb-48f5-a473-49695501bdaa.png)
i'm getting this error trying to get the bot up

**Comment by PIK4BOO** [comment]
me too

**Comment by Damian2623232** [comment]
me too

**Comment by Zaarrg** [comment]
Updated the Bot, try to start the bot now. No need to download a new version.
