### ISSUE TITLE
Failed to launch the browser process!

### ISSUE THREAD

**Issue by yujispin990** [Zaarrg/TTVDropBot#14]
(node:7904) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn C:\Program Files (x86)\Google\Chrome\Application ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (C:\Users\yujis\Downloads\Compressed\TTVDropBot_2\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (C:\Users\yujis\Downloads\Compressed\TTVDropBot_2\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:185:85)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `TTVDropBot --trace-warnings ...` to show where the warning was created)
(node:7904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Zaarrg** [comment]
Well the bot fails at opening Google Chrome possible soultions would be:
make sure you provided a vaild Google Chrome path and also have Google Chrome installed.
Also make sure that u extract everthing out of the .zip file to a seperate Folder.

**Comment by yujispin990** [comment]
Alrighty,i will try try that right now.

**Comment by yujispin990** [comment]
Ah,i did not provide full path to the chrome.exe,should have recognize this silly mistake,very sorry but i got the bot to work now just gonna test if its 100% working,thanks @Zaarrg.Considered this issue fixed.
