### ISSUE TITLE
Things to do.....

### ISSUE THREAD

**Issue by MondoPIX** [Zaarrg/TTVDropBot#15]
at the end of each session it would be necessary to check all the channels to see who is live because the bot does not do it at the moment, and it would be necessary to put the user at the first session to mark the completed drops so the bot does not watch the channel with the completed drop

**Comment by Zaarrg** [comment]
Should be fixed/added with the release of [1.3.3](https://github.com/Zaarrg/TTVDropBot/releases)

- So regarding ur first request the bot does check the live status and checks every minute if the channel is still live or not atleast in 1.3.3, there may was a bug in 1.3.2 were it didnt reload the status page and therefor didn't get a updated list.
- And regarding ur second request to check completed/claimed Drops this was added in 1.3.3.
