### ISSUE TITLE
Missing 2 streamers - Cyr and Sonii

### ISSUE THREAD

**Issue by Reserton** [Zaarrg/TTVDropBot#17]
Usually there is only 9 drops. But this time there is 11. https://twitch.facepunch.com/

It seems your program stops checking at 9, so is missing Cyr and Sonii off the streamer list. Possibly needs to be amended to check for larger streamer lists for these instances.

Getting all Drops and other Details

https://www.twitch.tv/Myth | Myth Assault Rifle | Live

https://www.twitch.tv/Voyboy | Voyboy Hammer | Offline

https://www.twitch.tv/xQcOW | xQc SAR | Offline

https://www.twitch.tv/AriaSaki | Ariasaki Hammer | Live

https://www.twitch.tv/Sykkuno | Sykkuno Assault Rifle | Offline

https://www.twitch.tv/ludwig | Ludwig Sleeping Bag | Offline

https://www.twitch.tv/pokimane | Pokimane Painted Garage Door | Offline

https://www.twitch.tv/Trainwreckstv | Trainwreckstv Combat Knife | Offline

https://www.twitch.tv/Account%20Not%20Found | WillNeff Burlap Headwrap | Offline

Checking for Live Channels

**Comment by Zaarrg** [comment]
Fixed with the newest release of [1.3.3](https://github.com/Zaarrg/TTVDropBot/releases)
