### ISSUE TITLE
Bot getting reset after 2 try

### ISSUE THREAD

**Issue by ravicant** [Zaarrg/TTVDropBot#2]
not able to get current progress and after 2 try it reset

**Comment by Zaarrg** [comment]
Well this is caused if the Drop Progress cannot start or is can not even be listed. Check if the Drop you wanna get is listed in https://www.twitch.tv/drops/inventory 
If its listed there with 0% or something else it should work. 
If its not listed try to watch the channel on your pc until it starts showing up with 0% or bigger, then try to switch back to the bot.
