### ISSUE TITLE
Can't login in time

### ISSUE THREAD

**Issue by tw0zh** [Zaarrg/TTVDropBot#22]
Using the new 1.3.3 version and I am getting this error after sucefully login into my account.
![image](https://user-images.githubusercontent.com/26041065/126052632-764754a3-7135-4364-a12d-7d5206682d0f.png)
Any fix?

**Comment by Zaarrg** [comment]
Check if you have any unread notifications on twitch.tv

**Comment by tw0zh** [comment]
I managed to fix it, thanks anyway.
I just needed to login to the twitch with the normal browser and allow all the cookies in the settings.
