### ISSUE TITLE
Program closes when adding a profile path

### ISSUE THREAD

**Issue by Reserton** [Zaarrg/TTVDropBot#24]
Tested on mine and friends PC now, and when adding the profile path after adding the chrome.exe path, the program just closes.

However editing the settings file and manually adding the path to that works fine.

Not sure what causes it to auto close during setup.

**Comment by Zaarrg** [comment]
Well it closes only if the chrome path is incorrect. It cant read the chrome.exe in this case or start it then it errors and closes. If the profile path is incorrect the bot creates one and does not cause an error. Try out the new version [1.3.3.1](https://github.com/Zaarrg/TTVDropBot/releases/tag/1.3.3.1) and check if the issues still occurs, the bot also suggest you a chrome path this way u can avoid providing a wrong one, if the bot finds the correct one.

**Comment by Reserton** [comment]
Its a little strange as both me and my friend copied and pasted it from chrome://version

and used the same path with double slashes // when manually editing.

However yes this is now fixe din 1.3.3.1 so I will close this off.
