### ISSUE TITLE
Auto Claim Not Working

### ISSUE THREAD

**Issue by Stiphr** [Zaarrg/TTVDropBot#27]
next stream is not starting because of auto claim

**Comment by Zaarrg** [comment]
Can u describ your issue a bit more or porvide screenshots its not really self explaing...

**Comment by Stiphr** [comment]
After 100% it doesn't automatically claim item and each time i open bot it asks for login details

**Comment by Zaarrg** [comment]
Well to get rid of the login you need to provide a user data directory if u provided a wrong one then chrome also doesnt save your login. And the bot does not claim your Drops it watches them until 100% and then switches channel, you have to manually claim the drops in the invetory by urself
