### ISSUE TITLE
Stuck on stream when it goes offline

### ISSUE THREAD

**Issue by D3XX3R** [Zaarrg/TTVDropBot#3]
If the stream you are "watching" goes offline you are stuck in the watching loop.
Makes the whole script useless when you want to idle while sleeping.

**Comment by Zaarrg** [comment]
Hm weird, there is a check implemented which checks every time the progress is displayed if the channel is offline and if its offline it looks for new ones, just tested it and it worked fine for me. 
Well ill add a Check which Checks if the percentage stayed the same for the last 4 progress displays and then look for a new channel. This should be a workaround in case the offline Check doesnt fire.
