### ISSUE TITLE
Auto reconnect on connection loss

### ISSUE THREAD

**Issue by Nipeno** [Zaarrg/TTVDropBot#37]
In case someone loses connection, retry every like 10 seconds and try to connect again.
At the moment the bot just kills itself.

**Comment by Zaarrg** [comment]
Probably will not add any built in feature for that you should use a process manager like pm2 for that to handle the error (connection lost) and restart the bot. You can use the [displayless ](https://github.com/Zaarrg/TTVDropBot#displayless) mode for that allowing the bot to work fully automatic and no need for any user input.

**Comment by Zaarrg** [comment]
Added with version [2.0.0.2](https://github.com/Zaarrg/TTVDropBot/releases/tag/2.0.0.2)
See Changelog:

> - Added Retries, Bot now retries 3 times with a delay of 30 seconds in between, if a request fails
