### ISSUE TITLE
Cannot read get property "getProperty" of undefined

### ISSUE THREAD

**Issue by arisawali2014** [Zaarrg/TTVDropBot#4]
![image](https://user-images.githubusercontent.com/31904944/110572217-97abfb80-818b-11eb-82e8-417faceab826.png)
i got this error after getting twitch channel

**Comment by Zaarrg** [comment]
Fixed in Release 1.2-hotfix
Caused by Design change of 'https://twitch.facepunch.com/' which caused xpaths to be invaild
