### ISSUE TITLE
unCaughtExeption: waiting for selector

### ISSUE THREAD

**Issue by Plastic-Hair** [Zaarrg/TTVDropBot#42]
![Screenshot (2)](https://user-images.githubusercontent.com/95957317/153506630-a28f15a5-3204-4958-b0f9-9c2eb8c6de3c.png)

couldn't copy text since it auto-closes.
Not sure what its trying to do but it keeps timing out

**Comment by Zaarrg** [comment]
Rust moved all drops to general, will realease fix asap

**Comment by Zaarrg** [comment]
Nvm, ur issue is caused by something not loading on the Twitch/inventory page, try increasing/changing the timeout in the settings file or try launching with headless false to see what happens. Make sure u are using the newest version.

**Comment by Zaarrg** [comment]
Updated to [v2](https://github.com/Zaarrg/TTVDropBot/releases/tag/2.0.0.0). Error irrelevant cause remade bot.
