### ISSUE TITLE
Send webhooks on events (enhancement)

### ISSUE THREAD

**Issue by Hirashi3630** [Zaarrg/TTVDropBot#46]
Hi!
I'm running TTVDropBot on server and I'd like it to send webhooks on checks (fe. every so often or on claimed drop...)

_for example Discord Webhook_
![image](https://user-images.githubusercontent.com/37778278/160082065-0414bab4-a9ac-42a9-afec-de77d5cc18ec.png)

I don't know typescript but I've worked with webhooks before so I can help at least with that!

**Comment by Zaarrg** [comment]
Thanks for the suggestion, i will look into it and add webhooks in the next version, if i need any help ill let you know.

**Comment by Zaarrg** [comment]
Added Webhooks in version [2.0.0.3](https://github.com/Zaarrg/TTVDropBot/releases/tag/2.0.0.3)

**Comment by Hirashi3630** [comment]
tested today and works like charm!
thanks
