### ISSUE TITLE
[QUESTIONS] About offline-streams

### ISSUE THREAD

**Issue by slhrlx** [Zaarrg/TTVDropBot#5]
if I start the program while the streams is offline, when he go online, the program automatically start watching? or, I need do something for he do that?

2. That's program works on heroku? if yes, you can add a button to easy deploy here on github :D

**Comment by Zaarrg** [comment]
It depends, if for example you are at 50% progress watching someone then the bot will watch until 100% and then look for a new channel. Every time the bot "Looks for a new Channel" it gets all Channel Status. If for example all channels offline the bot will "look for a new Channel" Every ten minutes and while looking also checking the status. So basicly u dont have to do anything the bot will always try to watch a online channel and to stop "watching/progress" if the channel is offline.

2. It should work on heroku, i would need to test that im not sure tho if it will work. Im not really using github a lot so didnt know thats a thing but thanks for telling me. I'll try to add a button if i test the bot on heroku sucessfully.
