### ISSUE TITLE
Twitch URL Interpreted as Invalid

### ISSUE THREAD

**Issue by hifocus** [Zaarrg/TTVDropBot#53]
## Steps to reproduce
```bash
git clone https://github.com/Zaarrg/TTVDropBot
cd TTVDropBot
yarn install
yarn start:production
```

Select custom channel - Warframe
Enter url: `https://twitch.tv/warframe`

`>> Please provide a Valid URL...`

Similarly, yesterday while Warframe was live, the current dev channel cannot be auto-watched correctly (Select Warframe Campaign - Prime Time xxx) - it returns an error similar to #50, I recall it was something to do with the GAMEID, but I've lost my log due to a restart. Other channels/campaigns seemed to be fine.

![image](https://user-images.githubusercontent.com/30528433/164628657-1f26bc8f-f275-465f-ae66-171f5b635779.png)

```
No Custom Channels Found...
? Do you wanna add a Custom Channel? Yes
? Please provide a Name for this Custom Channel: r6
? Please provide the Twitch Url: https://twitch.tv/rainbow6
>> Please provide a Valid URL...
```

**Comment by Zaarrg** [comment]
As also mentioned in the section [Adding-Custom-Channels](https://github.com/Zaarrg/TTVDropBot#-adding-custom-channels) in the readme, you are missing the www.
A vaild url Looks like this: `https://www.twitch.tv/xqcow`

**Comment by DreamPhreak** [comment]
A vaild url Looks like this: `https://www.twitch.tv/xqcow`

URLs without www are still valid too, why not accept them here?
