### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by jaredkotoff** [Zaarrg/TTVDropBot#54]
I run a bunch of stuff like this with docker-compose
So I would love official support/instructions for docker/docker-compose

**Comment by AusHick** [comment]
https://github.com/Zaarrg/TTVDropBot/pull/56

If this gets approved, then it should be available by default. If you are in a hurry to get it yourself, you can always just clone, and build yourself.

**Comment by Zaarrg** [comment]
#56 Merged, thanks a lot for the pull request
