### ISSUE TITLE
The bot can't read property 'getProperty' again

### ISSUE THREAD

**Issue by LudovicoSforza** [Zaarrg/TTVDropBot#6]
Here's the screenshot
![Screenshot from 2021-04-14 00-59-10](https://user-images.githubusercontent.com/44255157/114599211-031e4700-9cbd-11eb-9b74-b5b52d6d79db.png)

**Comment by Zaarrg** [comment]
Yeah that's normal Bot will Error until new Drops are avaiable to get. The Bot gets the Drops from https://twitch.facepunch.com/ if there are no Drops on the Site the bot will not work also means there are no Drops to get.
