### ISSUE TITLE
Are there any forks or alternatives to run on arm64?

### ISSUE THREAD

**Issue by AJConnelly** [Zaarrg/TTVDropBot#85]
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/local/bin/docker-entrypoint.sh: exec format error

**Comment by sffxzzp** [comment]
try [my build](https://github.com/sffxzzp/TTVDropBot-Build)?

**Comment by thierrybla** [comment]
> try [my build](https://github.com/sffxzzp/TTVDropBot-Build)?

Sadly no docker :(

**Comment by sffxzzp** [comment]
> > try [my build](https://github.com/sffxzzp/TTVDropBot-Build)?
> 
> Sadly no docker :(

Added. with only linux/arm64 and linux/amd64 support.

**Comment by thierrybla** [comment]
> > > try [my build](https://github.com/sffxzzp/TTVDropBot-Build)?
> > 
> > 
> > Sadly no docker :(
> 
> Added. with only `linux/arm64` and `linux/amd64` support.

You are my hero, thanks a lot!

**Comment by AJConnelly** [comment]
> try [my build](https://github.com/sffxzzp/TTVDropBot-Build)?

Thanks for this build it works! Now I don't have to run the pip version on an always open terminal.
